service: serverless-github-check

provider:
  name: aws
  runtime: nodejs8.10
  profile: personal
  region: eu-west-1
  environment:
    GITHUB_WEBHOOK_SECRET: ${ssm:webhookToken}

functions:
  githubListener:
    handler: handler.githubListener
    events:
      - http:
          path: webhook
          method: post
          cors: true

